name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - tqdm
  - matplotlib
  - ipykernel
  - pip
  - pip:
      - tqdm
      - matplotlib